"""add_ticket_performance_indexes

Revision ID: 0217e2a5ae75
Revises: 071619814285
Create Date: 2026-09-22 13:23:18.757606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0217e2a5ae75'
down_revision: Union[str, None] = '071619814285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_tickets_assigned_agent_status', 'tickets', ['assigned_agent_id', 'status'], unique=False)
    op.create_index('idx_tickets_customer_created', 'tickets', ['customer_id', 'created_at'], unique=False)
    op.create_index('idx_tickets_department_status', 'tickets', ['department_id', 'status'], unique=False)
    op.create_index('idx_tickets_priority', 'tickets', ['priority'], unique=False)
    op.create_index('idx_tickets_status', 'tickets', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tickets_status', table_name='tickets')
    op.drop_index('idx_tickets_priority', table_name='tickets')
    op.drop_index('idx_tickets_department_status', table_name='tickets')
    op.drop_index('idx_tickets_customer_created', table_name='tickets')
    op.drop_index('idx_tickets_assigned_agent_status', table_name='tickets')
    # ### end Alembic commands ###
