"""isActive_default

Revision ID: 2806888b0559
Revises: ab2bef3bd1d5
Create Date: 2026-09-19 23:29:12.325910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2806888b0559'
down_revision: Union[str, None] = 'ab2bef3bd1d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_public_users_auth_users'), 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_public_users_auth_users'), 'users', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    # ### end Alembic commands ###
