"""add_index_to_replies_ticket_id

Revision ID: c9684f140e9a
Revises: d7fce8d84455
Create Date: 2026-10-02 21:12:05.001391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9684f140e9a'
down_revision: Union[str, None] = 'd7fce8d84455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_replies_ticket_id'), 'replies', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replies_ticket_id'), table_name='replies')
    # ### end Alembic commands ###
