"""make_agent_tier_nullable

Revision ID: f130fcd61d04
Revises: ba13179dc751
Create Date: 2026-09-19 23:58:04.329841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f130fcd61d04'
down_revision: Union[str, None] = 'ba13179dc751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'agent_tier',
               existing_type=postgresql.ENUM('1', '2', name='agent_tier'),
               nullable=True,
               existing_server_default=sa.text("'1'::agent_tier"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'agent_tier',
               existing_type=postgresql.ENUM('1', '2', name='agent_tier'),
               nullable=False,
               existing_server_default=sa.text("'1'::agent_tier"))
    # ### end Alembic commands ###
